cds-snc/covid-alert-server-staging-terraform

.github/workflows/terraform.yml, server/aws/elasticache.tf, server/aws/networking.tf
This PR adds an elasticache (Redis) cluster to the infrastructure. It uses the existing private subnet that is used by the DB and fargate instances to communicate. It sets up a security group that allows communication between the redis cluster and the containers. It also has 3 replicas, one for each security group.
=> feat(redis): Adds the redis cluster

server/aws/elasticache.tf
T2 instances are not available in ca-central-1d so we should try t3.
=> Set t3 instead of t2

server/aws/cloudfront.tf, server/aws/s3.tf
The mobile app requires a pre-flight check for CORS to access the items in the exposure-configuration S3 bucket. This PR adds the CORS options to the S3 bucket and also configures cloudfront to pass those headers and values back out.
=> feat: Add CORS to S3 bucket and pass through cloudfront

server/aws/ecs.tf, server/aws/task-definitions/covidshield_key_retrieval.json
Exposes the Key Claim Token to the retrieval service so it's able to translate tokens.
=> fix(event): Expose key claim token to Retrieval service

server/aws/iam.tf
Allows the Key-Retrieval server to read the Secret storing the bearer tokens.
=> fix(event): Allow retrieval server to read the secret

server/aws/ecs.tf, server/aws/iam.tf, server/aws/secrets.tf
Adds Metrics Password to Secrets Manager
Adds Metrics Password ARN to Key-Submission IAM
Adds arn to ECS TF instead of passing the password as plain text
=> fix: Save metrics password to secret manager

server/aws/route53.tf
Wildcard certs do not cover sub-subdomains.
=> fix: change new ALB domain name

server/aws/variables.auto.tfvars
This is their standard instance current generation burstable 
Price difference can be seen here: 
https://aws.amazon.com/rds/pricing/
Available options are here:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html
=> scaling down to t3 to save money.

server/aws/cloudfront.tf, server/aws/ecs.tf, server/aws/iam.tf, server/aws/secrets.tf, server/aws/task-definitions/covidshield_key_retrieval.json, server/aws/task-definitions/covidshield_key_submission.json
Due to the requirement to vastly increase the number of IPs that need to be safelisted for event automation I've decided to move the events endpoint from the submission to the retrieval server. 
This PR needs to occur before the covid-alert-server pr occurs.
https://github.com/cds-snc/covid-alert-server/pull/321
=> feat: moving events from sub to ret

server/aws/cloudfront.tf, server/aws/ecs.tf, server/aws/iam.tf, server/aws/secrets.tf
Fixes the references to the secret, we cannot just rename TF resources
Fixes the issue with the cloudfront forwarding not having the HEAD verb
=> fix: add HEAD for CF and fix name of secret

server/aws/cloudfront.tf
Added get and head to cache headers, hopefully the fact that TTL is 0 this shouldn't cache
=> fix: add cached headers

server/aws/cloudfront.tf
Forwards the auth header as cloud front stripped it out
Add a default TTL of 0 so it never caches
=> fix: fwd auth header, add default_ttl = 0

server/aws/certificates.tf
Attempt to fix the issue with TF Apply complaining about a validation
already existing by removing the existing record from TF State and
allowing it to overwrite the existing validation rule:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate
>In larger or more complex environments though, this process can be tedius to match the old resource address to the new resource address and run all the necessary terraform state mv commands. Instead, since the aws_route53_record resource implements the allow_overwrite = true argument, it is possible to just remove the old aws_route53_record resources from the Terraform state using the terraform state rm command. In this case, Terraform will leave the existing records in Route 53 …
=> fix: Add allow_overwrite = true

server/aws/ecs.tf, server/aws/task-definitions/covidshield_key_retrieval.json, server/aws/variables.auto.tfvars, server/aws/variables.tf
Add the ENABLE_TEST_TOOLS flag to staging to enable the endpoint that clears the diagnosis_keys table
=> feat: Add enable_test_tools flag to retrieval svc

server/aws/cloudwatch.tf
Adds an alert if `clearDiagnosisKeys` is called. This will trigger slack notifications in staging and trigger an Ops page in production as this should never happen in production.
=> feat: add alarm is diagnosis_keys clear was called

server/aws/ecs.tf, server/aws/task-definitions/covidshield_key_retrieval.json, server/aws/task-definitions/covidshield_key_submission.json, server/aws/waf.tf
Adds a WAF rule similar to `new-key-claim` that allows the calling of `/clear-diagnosis-keys` from the safelisted IPs
=> feat: Add WAF rule for clear keys URI

server/aws/ecs.tf, server/aws/variables.auto.tfvars, server/aws/variables.tf
Scale down the retrieval and submission ECS service and Task Defintions
Scale down the ECS service to only 1 fargate instance running at a time. 
Scale down to 1 CPU as we currently avg less than a percentage of CPU utiliziation in staging
Scale down to 1 gig of ram as we avg around 7mb of ram usage. 
**Please Note:** We can probably scale this service down even more however I want to slowly work at this so we aren't negatively affecting staging too much
=> feat: Scale down ECS Task Def's and Service

server/aws/variables.auto.tfvars
Scale down to 0.5 vcpu and 1 gig of ram per fargate instance
=> Feat: Scale down to half a virtual cpu

server/aws/variables.auto.tfvars
Scale to the lowest instance of the current gen burstable db's
**Please Note: This will only take effect during the next maintenance period for DBs**
Related: https://github.com/cds-snc/covid-alert-server/issues/338
=> feat: downscale Aurora in staging to smallest current gen

.github/workflows/sync-labels.yml
Use the cds-snc/covid-alert-server-labels action to keep the labels in sync across all covid alert server projects.
=> docs: sync labels across projects

server/aws/ecs.tf, server/aws/lb.tf, server/aws/s3.tf
Remove the autoscale configurations for ECS since those haven't worked
since we implemented green/blue deploys it's also not needed due to
current server utlization.
Add CBS logging so we stop polluting PR's with uneeded infra changes
Closes #64 
Closes https://github.com/cds-snc/covid-alert-server/issues/352
=> feat: remove autoscaling configs & reconcile CBS

server/aws/waf.tf
Turn back on rate limiting since we are done stuffing the database
Associated with cds-snc/covid-alert-server#390
Undoing #66
=> chore: renable rate limiting

.github/workflows/terraform.yml, server/aws/.terraform.lock.hcl, server/aws/.tool-versions, server/aws/provider.tf
Upgrade to the latest version of Terraform (v0.14.2). 
This fixes a known slowdown due to using WAFv2 our plans should go from 15 minutes down to 20 seconds
Closes #69 
Closes #37 
BREAKING CHANGE: Terraform state files are not backwards compatible.
=> feat: upgrade Terraform to v0.14.2

server/aws/mc-api-gateway.tf, server/aws/mc-lambda.tf, server/aws/mc-s3-buckets.tf, server/aws/mc-variables.tf, server/aws/mc-waf.tf
This Terraform deploys the architecture shown in the image below. It is a WAF secured API Gateway with one POST method for calling a Lambda function that will take a JSON payload of metrics information and place it in an encrypted S3 bucket. The encryption used is AWS Key Management Service (KMS) Customer Managed Key (CMK). issue #74 
-The POST method requires an APIKey that is auto-generated and infrastructure deployment. 
-The Lambda function code is pulled from an S3 bucket deployed via CICD from the Covid Server repository.
-The Lambda function requires 3 environment variables, dataKey : auto-generated from Terraform, dataBucket : the bucket that will receive the  metrics objects: target in mc-variables.tf file and fileLoca : the prefix of the dataBucket where the Raw metrics will …
=> feat(submission) infrastructure deployment for metrics collection service

server/aws/mc-api-gateway.tf, server/aws/route53.tf
This PR adds a domain name: `metrics.${aws_route53_zone.covidshield.name}` to the system which hooks up to a lambda available through the API gateway and uses the existing wildcard SSL certificate for HTTPS.
=> feat: adds a domain name to the metrics collection lambda

server/aws/mc-api-gateway.tf
Adds an explicit REGIONAL designation to the API gateway domain. Also adds a `aws_api_gateway_base_path_mapping` resource to link the base domain to the path.
=> fix: explicitly add REGIONAL designation and add base path mapping

server/aws/mc-lambda.tf
This PR adds a `prefix_list` to the security group handling the outbound traffic from the metrics lambda to S3. The S3 private link to our VPC is a gateway and not attached through an ENI like many other private links. As a result it does not get an IP address inside our VPC.
=> fix: adds proper egress to lambda SG

server/aws/mc-api-gateway.tf, server/aws/models/metrics.json
Adds a JSON Schema model and validates call to Lambda with it. 
Schema was created by taking the following JSON doc: 
```
{
"metricstimestamp": 1611324826295,
"appversion": "999",
"appos": "ios",
"payload": [{
"identifier": "installed",
"region": "None",
"timestamp": 1611323998012
},
{
"identifier": "onboarded",
"region": "QC",
"timestamp": 1611324024314,
"pushnotification": "true",
"frameworkenabled": "true"
},
{
"identifier": "exposed",
"region": "QC",
"timestamp": 1611324820294
},
{
"identifier": "otk-no-date",
"region": "QC",
"timestamp": 1611324825778
},
{
"identifier": "otk-with-date",
"region": "QC",
"timestamp": 1611324825778
},
{
"identifier": "en-toggle",
"region": "QC",
"timestamp": 1611324825778,
"state": "true"
},
{
"identifier": "exposed-clear",
"region": "QC",
"timestamp": …
```
=> feat: model for JSON Schema Validation

server/aws/lambda/create_metric.js, server/aws/mc-lambda.tf, server/aws/mc-variables.tf
This PR changes the create metrics lambda into a simple script without any dependencies. The previous deploy method method included 8 MB of dependencies such as the AWS client and a UUID function which could easily be loaded from the environment in the case of the former, and replaced by a function in the case of the later.
=> feat: stashes create metrics script inside TF

server/aws/mc-variables.tf
rename the service, FYI this will recreate entire metrics service
=> feat: rename service to not reference org

server/aws/lambda/create_metric.js, server/aws/mc-api-gateway.tf
Convert save-metrics lambda to an AWS Lambda Proxy
Instead of using integration mapping to map results from the lambda to
specific error codes and return values it just leverages the "Empty" and
"Error" models for 200 and 500 errors respectively which pass through
the return json to the client
AWS reccomends that all new lambda's be built using lambda proxys and so
that's what this does.
TF Plan output to make sure nothing untoward happens
=> feat: convert to lambda proxy

server/aws/lambda/create_metric.js, server/aws/mc-api-gateway.tf
Instead of logging the entire payload we only log the body. 
Add a variable to the deployment resource so it always deploys on a plan. This will probably be removed when we decouple the lambda code.
=> fix: only log body, and force a deploy of lambda

server/aws/lambda/create_metric.js
This will remove all the whitespace and pack it as tightly as possible,
to make it smaller we will need to compress or change to a different
data structure such as protobufs.
=> feat: parse json before stringifying and storing

server/aws/mc-api-gateway.tf
Because we are using an AWS_PROXY integration responses are just a pass
through, no transforms required. This resource should be 100% unused.
=> feat: remove unused integration response

server/aws/cloudfront.tf, server/aws/s3.tf
This PR creates another S3 bucket to serve static files from the `.well-known` path. This is to facilitate the work being done in https://github.com/cds-snc/covid-alert-exposure-configuration-staging/pull/71
=> feat: adds a .well-known dir to retreival for app redirect

server/aws/lambda/create_metric.js
String is S not s
Need to call `.promise()` on the dynamodb call or it doesn't work
properly
=> fix: fix errors in lambdas

server/aws/lambda/aggregate_values.js, server/aws/lambda/create_metric.js, server/aws/modules/metrics/iam_policies.tf
Pre-aggregates events that are coming in from the event stream to reduce writes to the aggregate_metrics table
Properly set TTL on raw_metrics folder
Provide proper permissions to the aggregator on the aggregate_metrics table.
=> fix: work on aggregate functionality

server/aws/modules/metrics/aggregator.tf
=> fix: use proper resource name when creating log group

server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/aggregator_iam.tf, server/aws/modules/metrics/iam_policies.tf
We had neglected to attach the policy allowing updates of the
aggregation table to the lambda.
Add a curly-brace that had dissapeared.
=> fix: attach update policy to aggregator

server/aws/in-app-metrics.tf, server/aws/modules/metrics/aggregator.tf, server/aws/modules/metrics/variables.tf, server/aws/networking.tf
Adds a SQS private link and allows the metrics lambda to access the SG that those endpoints are connected to.
=> feat: add private link to SQS/KMS

server/aws/modules/metrics/backoff_retry.tf
Sets the execution role for the lambda to the intended one.
=> fix: assigns backoff lambda the correct role

server/aws/modules/metrics/iam_policies.tf
This PR adds the `sqs:DeleteMessage` permission to the backoff role.
=> fix: add DeleteMessage permission

server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/iam_policies.tf
Since we parseInt before we add to the aggregates or update the count it should always be a number and not a string anymore.
=> fix: remove the uneeded missing method

server/aws/networking.tf
Closes #135.
This PR removes the default ingress and egress rules on the default security group for the VPC by adopting it into TF management. As nothing should be using the default security group, this should have no impact.
=> feat: remove ingress and egress for default security group

server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/dynamodb.tf
pk is now the region instead of a hash
sk is now the following:
`${pl.region}#${pl.identifier}#${pl.date}#${appos}#${appversion}`
We didn't need to hash the primary key, the region should be enough for
our needs.
=> feat: update pk and sk

server/aws/lambda/aggregate_values.js
- Add the date to the payload
- calculate the pinned date before we add to aggregates so it's not
undefined in the SK.
- Format the date in the sk as an ISO date string, it's pinned to
midnight so safe to just store the yyyy-MM-dd
=> fix: use ISO date format

server/aws/modules/metrics/aggregator.tf, server/aws/modules/metrics/backoff_retry.tf
This moves an egress definition between the metrics aggregation lambda security group and the private link security group to the initial definition of the aggregations. We noted that the second definition was never applied.
=> fix: move egress block to initial definition

server/aws/lambda/aggregate_values.js, server/aws/lambda/backoff_retry.js, server/aws/modules/metrics/aggregator.tf
- Replace synchronous await calls with asynchronous calls
- Reuse a connection between all DynamoDB calls
- Increase timeout for lambda to 1 minute (60 seconds)
- Replace ADD update command with SET as per AWS recommendations
=> fix: use asynchronous sdk calls reuse connection

server/aws/cloudwatch.tf, server/aws/in-app-metrics.tf, server/aws/mc-variables.tf, server/aws/modules/metrics/alerts.tf, server/aws/modules/metrics/variables.auto.tfvars, server/aws/modules/metrics/variables.tf, server/aws/variables.auto.tfvars
This PR adds the terraform for alerts around our metrics infrastructure. These include:
- More then X 500 error
- under X invocations a minute
- over X invocations a minute
- WCU per minute for raw_metrics 
- WCU per minute for aggregate_metrics
- invocation time for raw_metrics
- invocation time for aggregate_metrics
Threshold adjustments can be made to 
server/aws/variables.auto.tfvars
=> feat: terraform alerting around metrics infrastructure

server/aws/modules/metrics/ec2_data_module.tf
This PR adds a new EC2 instance to the metrics module that can be used to generate report data for distribution. The EC2 instance is added by a custom CDS module.
=> feat: add EC2 instance to metrics module using CDS EC2 module

server/aws/modules/metrics/ec2_data_module.tf
Fixes an issue where we were trying to create a route to the Dynamodb private link on the route table that is not needed as the VPC Private Link makes it's own route.
=> fix: update to latest module version

server/aws/in-app-metrics.tf, server/aws/modules/codedeploy/variables.tf, server/aws/modules/metrics/dashboard.tf, server/aws/modules/metrics/ec2_data_module.tf, server/aws/modules/metrics/variables.tf
Closes https://github.com/cds-snc/covid-alert-server-staging-terraform/issues/161. This PR creates a dashboard around operation metrics for the metrics collection service. It includes
- Total API calls for a 3 hour period
- number of 5XX errors
- number of 403 errors
- API calls over time
- 5xx and 403 errors over time
- Read and Write capacity units for raw_metrics and aggregate_metrics table
- Count of Lambda errors over time
=> feat: Add ops dashboard for metrics service

server/aws/cloudfront.tf, server/aws/s3.tf
Closes https://github.com/cds-snc/covid-alert-server-staging-terraform/issues/173 and reverses https://github.com/cds-snc/covid-alert-server-staging-terraform/pull/109. 
We never ended up using this feature.
=> feat: removes well-known bucket

.github/workflows/terraform.yml, server/aws/cloudwatch.tf, server/aws/in-app-metrics.tf, server/aws/modules/metrics/alerts.tf, server/aws/modules/metrics/variables.tf, server/aws/s3.tf, server/aws/variables.auto.tfvars, server/aws/variables.tf
Adds a feature flag to turn off alarms that have a tendency to go off
during the collection of debug metrics.
The reason for turning this off versus just increasing metric count is
that we have so far been pretty bad about being able to predict traffic
patterns with debug metrics turned on.
We should be able to determine failure of the metrics collection service
through other means such as an increase in errors or a drop off of
invocations.
closes #193
=> feat: add a feature flag for count alarms

server/aws/modules/metrics/s3.tf
Use valid s3 bucket names which caused the last apply to fail with the following error: 
>Error: Error validating S3 bucket name: only lowercase alphanumeric characters and hyphens allowed in "masked_metrics-mV_U1-***"
=> fix: use valid s3 bucket names

server/aws/modules/metrics/s3.tf
Apparently I forgot the difference between a hyphen and an underscore, this PR fixes that problem.
=> fix: use hyphens not underscores in s3 name

server/aws/modules/metrics/s3.tf
Gives both s3 buckets for csv metrics unique names, not sure this will fully pass when applying as we also had a lambda error.
=> fix: give metric buckets unique names

server/aws/cloudwatch.tf, server/aws/variables.auto.tfvars
Use the latency metric for the latency alarm
Closes #197
=> fix: ruse proper metric for alarm

server/aws/modules/metrics/create_csv.tf, server/aws/variables.auto.tfvars
- Changes to (un)+masked_metrics
- Removed `runtime` from lambdas
- Added `package_type` = `Image` as it defaults to `Zip`
- Increased API GW Latency alarm so staging isn't constantly pinging
*Please Note:* lambda metrics have already been applied in staging
Closes #208
Closes #207
=> fix: lambda deployment

server/aws/.tfsec/config.yml, server/aws/modules/metrics/ec2_data_module.tf
This is being replaced by the CSV ETL Lambdas in the
[cds-snc/covid-alert-metrics-terraform](https://github.com/cds-snc/covid-alert-metrics-terraform) project.
=> feat: remove metrics data VM

.devcontainer/Dockerfile
This will let us use our local `git config core.editor "vim"` setting in the devcontainer.
=> feat: add vim to devcontainer

server/aws/models/metrics.json
The API gateway is rejecting metric payloads with an appversion that is longer
then 5 characters.
This allows for a 10 character appversion in the payload.
=> fix: increase max length of metrics appversion

server/aws/modules/metrics/.terraform.lock.hcl, server/aws/modules/metrics/aggregator.tf, server/aws/modules/metrics/backoff_retry.tf, server/aws/modules/metrics/iam_policies.tf, server/aws/modules/metrics/kms.tf, server/aws/modules/metrics/sqs.tf
Replace SQS and KMS with Data Lookups as state is now managed in TG Repo
Please note this should not delete the SQS and KMS or modify other resources (other then deployment of lambdas).
=> feat: Migrate SMS and KMS Key to TG Repo

.github/workflows/s3-backup.yml
Adds a daily backup of the repo's code to an S3 bucket.  This will be used for disaster recovery if GitHub is unavailable.
Related cds-snc/site-reliability-engineering#194
=> feat: add daily s3 code backup

.devcontainer/devcontainer.json, server/aws/kms.tf
This will be used for data lookups in the covid-alert-metrics-terraform project.
Also adds Terraform format on-save to the devcontainer.
* 2 new KMS key aliases
* API gateway recreate
Related cds-snc/covid-alert-metrics-terraform#2
=> feat: add KMS key alias for easier data lookup

server/aws/variables.auto.tfvars
We've seen a number of alerts over the past week around 3.001 and 3.002 seconds so this should help take down the noise.
* Recreate `aws_cloudwatch_metric_alarm.save_metrics_average_duration` alarm with `10000` threshold.
=> feat: bump threshold for save metrics duration alarm

server/aws/mc-api-gateway.tf
Match the API gateway account name resource name to PROD.  The state move was done locally with:
```terraform
terraform state mv aws_api_gateway_account.demo aws_api_gateway_account.main
```
* Only the normal API gateway deployment and stage.
Fixes #184
=> fix: match API gateway account name to PROD

server/aws/lambda/aggregate_values.js, server/aws/lambda/aggregate_values.test.js
Handles Null and Empty Regions so it doesn't crash
Stringifies error so we actually use the dead letter queue
=> fix: handle empty region, stringify error for DLQ

server/aws/ecs.tf, server/aws/secrets.tf
This updates the key retrieval ECS task to use the RDS cluster's
read-only endpoint now that cds-snc/covid-alert-server#461 has
moved all DB write operations to the key submission task.
cds-snc/covid-alert-server-production-terraform#120
=> feat: key retrieval use RDS read-only endpoint

server/aws/task-definitions/covidshield_key_retrieval.json
This increases the open file limit to 65,535 to deal with the
increased time it's taking the key retrieval service to generate
TEK bundles.
By default ECS tasks have a soft limit of 1,024 open files.
cds-snc/covid-alert-server-production-terraform#120
=> fix: increase nofile ulimits for ECS retrieval task

server/aws/iam.tf
Gives the ECS key retrieval task access to the DB read-only URL secret.
#244 
cds-snc/covid-alert-server-production-terraform#120
=> fix: allow key retrieval task to access DB secret

README.md
Covid Alert is now retired.
Rendered version:
https://github.com/cds-snc/covid-alert-server-staging-terraform/blob/docs/decomm/README.md
=> docs: decomm message
