server/aws/cloudfront.tf, server/aws/s3.tf
=> fix(etag): Reverting work done to support etag

.github/workflows/terraform.yml, server/aws/ecs.tf, server/aws/task-definitions/covidshield_key_submission.json, server/aws/variables.tf
Adds some environment variables so we can deploy the events end point
=> feature: Add env variables for metrics pword an uname

server/aws/ecs.tf, server/aws/lb.tf, server/aws/route53.tf, server/aws/shield.tf, server/aws/waf.tf
Adds an additional application load balancer to the submission endpoint.
=> feat: add additional submission ALB

.github/workflows/terraform.yml
Fixes a bug where the workflow would hang if missing variables
=> fix: add  to stop blocking on stdin

.github/workflows/terraform.yml, bootstrap/.tool-versions, server/aws/.tool-versions, server/aws/cloudfront.tf, server/aws/kms.tf, server/aws/provider.tf, server/aws/rds.tf
Update TF Security Scan
Print TF plan in comments.
=> ci: improve tf

server/aws/provider.tf
Foundational PR for Container Lambda's
Closes #60
=> feat: upgrade aws provider to 3.21

.github/workflows/terraform.yml, server/aws/provider.tf, server/aws/variables.tf
Fixes the issue with TF Formatting failing
=> fix: only pass if all succeed

.github/workflows/terraform.yml, server/aws/mc-api-gateway.tf
=> fix: ran tf fmt

server/aws/mc-lambda.tf
Ran tf format in `./server/aws`
=> chore: format waf file (tool)

server/aws/mc-api-gateway.tf, server/aws/mc-lambda.tf, server/aws/mc-s3-buckets.tf, server/aws/mc-waf.tf
Removes tags that didn't match CDS standards
Replaces access logs for metric collection bucket with CBS access logging
=> fix: remove tags, add cbs access logging

server/aws/mc-api-gateway.tf
=> fix: remove non-alphanum from name

server/aws/mc-lambda.tf
Fixes the typo in the lambda name ZIP.
=> fix: lambda name

server/aws/mc-lambda.tf
Fixes the handler name on the lambda
=> fix: use correct handler

server/aws/mc-api-gateway.tf
=> fix: attach validator to POST

server/aws/mc-api-gateway.tf
=> fix: sync request model

server/aws/lambda/create_metric.js
This PR cleans up the metrics lambda with stylistic code changes. It also segregates saved date by YYYY-MM-DD inside the bucket.
=> feat: segregate by YYYY-MM-DD

server/aws/mc-api-gateway.tf
=> fix: change to empty

server/aws/mc-api-gateway.tf
=> fix: remove convert to text

server/aws/mc-api-gateway.tf
Applying fix found here: https://github.com/hashicorp/terraform/issues/10674#issuecomment-290767062 and used in Chalice here: https://github.com/aws/chalice/commit/e4a6884231889465561b4588e094cbfff62373e8
=> fix: using fix identified in GH

server/aws/mc-variables.tf
=> fix: remove unused and sync with prod

.github/workflows/terraform.yml, server/aws/in-app-metrics.tf, server/aws/lambda/create_metric.js, server/aws/modules/metrics/iam.tf, server/aws/modules/metrics/variables.tf
Add a policy
Write raw string to table
=> fix: allow lambda to put data into raw_metrics

server/aws/in-app-metrics.tf, server/aws/modules/metrics/iam.tf, server/aws/modules/metrics/variables.tf
=> fix: use role name instead of arn

server/aws/modules/metrics/iam_policies.tf
=> fix: allow aggregator to list db shards

server/aws/modules/metrics/iam_policies.tf
=> fix: use the stream_arn instead of the table arn

server/aws/modules/metrics/aggregator.tf
=> fix: use the correct log group name

server/aws/modules/metrics/iam_policies.tf
=> fix: create a better name

.github/workflows/terraform.yml, server/aws/lambda/aggregate_values.js
Adds an SK to the DynamoDB aggregate table
Adds the extra attributes of the event payload
=> feat: add date sk, and other metric attributes

server/aws/modules/metrics/dynamodb.tf
Required for aggregate table to work
=> fix: add date as secondary key on agg table

server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/aggregator.tf
If we fail to write to the aggregator table we need to save to a dead
letter queue.
=> feat: write to the dead letter queue

server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/aggregator.tf
Adds an additional security group egress and updates the lambda code for metrics aggregation.
=> fix: sg egress and code update

server/aws/lambda/aggregate_values.js
=> fix: use the proper method to create the SK

server/aws/lambda/aggregate_values.js
pinDate now returns the ISO String yyyy-MM-dd.
=> fix: date string is handled properly now

server/aws/waf.tf
This PR adds a WAF rule that allows access to the outbreak event submission endpoint, which is currently located under `/qr/new-event` on the submission server. The retrieval server also has an equivalent `qr` endpoint, however, does not require a similar exception as the WAF. The submission endpoint is retricted to the same IP set that the new key endpoint uses. More information can be found in this PR: https://github.com/cds-snc/covid-alert-server/pull/438
=> feat: QR event submission WAF rule

server/aws/lambda/aggregate_values.js, server/aws/lambda/backoff_retry.js, server/aws/lambda/create_metric.js
This will help us surface issues in our lambda's that we may have
otherwise missed.
=> feat: log to stderr when an exception is thrown.

.github/workflows/terraform.yml, server/aws/lambda/aggregate_values.js, server/aws/mc-api-gateway.tf
- Use sort key instead of aggregate key for pre-aggregation
- Add all potential extra attributes to the sort key so we bucket
properly
- Add a version attribute to the table
=> feat: fix aggregation issues.

server/aws/s3.tf
Adds the CloudFront ACL to the S3 bucket
=> fix: add CF ACL to logging bucket

server/aws/lambda/aggregate_values.js
Typo in the update expression causes it all to fail
=> fix: add a comma to updateExpression

server/aws/cloudwatch.tf, server/aws/lambda/aggregate_values.js, server/aws/modules/metrics/alerts.tf
Handles the following global attributes: 
-  manufacturer
- android release version
Buckets the following attributes 
- count on background-check
- duration on background-process
Changes alarms on duration to p99 from average
=> feat: handle new attributes

server/aws/lambda/aggregate_values.js, server/aws/lambda/aggregate_values.test.js
Don't aggregate ExposureNotificationCheck event
Add new attributes to metrics event
=> feat: add new attributes to event and ignore debug

server/aws/lambda/aggregate_values.js, server/aws/lambda/aggregate_values.test.js
Forgot to update the version number with the last PR.
=> feat: update the version to reflect it's new

server/aws/mc-variables.tf, server/aws/rds.tf, server/aws/s3.tf
- feat: use environment for CSB logs
- feat: add deletion protection to RDS
- feat: change api key name
Closes #174
=> feat: fix drift between staging and production

server/aws/modules/metrics/dynamodb.tf
Closes https://github.com/cds-snc/covid-alert-server-private/issues/18
=> feat: enalbe pitr on aggregate_metrics table

server/aws/lambda/aggregate_values.js, server/aws/lambda/aggregate_values.test.js
=> fix: track durationInSeconds and status

server/aws/in-app-metrics.tf, server/aws/modules/metrics/create_csv.tf, server/aws/modules/metrics/create_csv_iam.tf, server/aws/modules/metrics/iam_policies.tf, server/aws/modules/metrics/s3.tf, server/aws/modules/metrics/variables.tf, server/aws/variables.auto.tfvars, server/aws/variables.tf
Creates S3 buckets for metric csv to end up in 
Create 2 lambdas that are triggered by cloudwatch events
Create nsg's for those lambdas
=> feat: infrastructure for create_csv lambdas

server/aws/modules/metrics/create_csv.tf, server/aws/modules/metrics/s3.tf, server/aws/modules/metrics/variables.tf
=> fix: set special to false on string for s3 name

server/aws/in-app-metrics.tf, server/aws/modules/metrics/create_csv.tf, server/aws/modules/metrics/create_csv_iam.tf, server/aws/modules/metrics/ecr.tf, server/aws/modules/metrics/iam_policies.tf, server/aws/modules/metrics/variables.tf, server/aws/variables.auto.tfvars, server/aws/variables.tf
- Create a private ECR repo for create_csv container
- Attach a role to metrics IAM user so it can pull the image
- Update variables and remove old ones
=> fix: use internal ECR

server/aws/modules/metrics/iam_policies.tf
This will still fail on apply due to lack of containers in ECR repo
=> fix: remove broken sid

.devcontainer/devcontainer.json
This adds YAML linting to the devcontainer.
=> feat: add VS Code YAML extenstion

server/aws/variables.auto.tfvars
Enables metric alarms in staging
=> feat: enable staging alarms

server/aws/modules/metrics/aggregator.tf, server/aws/modules/metrics/alerts.tf, server/aws/modules/metrics/dashboard.tf, server/aws/modules/metrics/dynamodb.tf, server/aws/modules/metrics/iam_policies.tf, server/aws/modules/metrics/outputs.tf
These tables are being migrated over to the new Terragrunt repo and so
I've replaced them with lookups as state has been migrated
**Please Note:** This PR should not modify state other then expected values.
=> feat: replace dynamodb tables with lookups

.github/workflows/terraform.yml
Use [cds-snc/terraform-plan](https://github.com/cds-snc/terraform-plan) to run Terraform init, validate and plan.
* API gateway state
=> feat: use CDS Terraform plan GitHub Action

.github/workflows/terraform.yml
Upgrade Terraform plan GitHub action to latest release.
=> chore: bump terraform plan action to v1.0.4

.github/workflows/s3-backup.yml, .github/workflows/terraform.yml
Update all default branch references to `main`.
Closes #217
=> feat: rename default branch to `main`

server/aws/kinesis.tf, server/aws/lb.tf, server/aws/s3.tf, server/aws/task-definitions/covidshield_key_retrieval.json, server/aws/task-definitions/covidshield_key_submission.json, server/aws/variables.auto.tfvars, server/aws/variables.tf, server/aws/vpc_flow_log.tf
Update S3, WAF ACL, load balancer and VPC logs to use new Cloud Based
Sensor satellite bucket.
* Closes cds-snc/cloud-based-sensor#61
=> feat: send logs to new Cloud Based Sensor bucket
